KOBJS += kernel/bootstrap.o \
         kernel/main.o \
         kernel/gdt.o \
         kernel/utils.o \
         kernel/system.o \
         kernel/arch.o \
         kernel/idt.o \
         kernel/interrupts.o \
         kernel/vga.o \
         kernel/pic.o \
         kernel/pit.o \
         kernel/vsprintf.o \
         kernel/string.o \
         kernel/pmm.o \
         kernel/vmm.o \
         kernel/serial.o \
         kernel/logging.o \
         kernel/keyboard.o
