KOBJS += kernel/bootstrap.o \
         kernel/main.o \
         kernel/gdt.o \
         kernel/utils.o \
         kernel/system.o \
         kernel/arch.o \
         kernel/idt.o \
         kernel/interrupts.o \
         kernel/vga.o \
         kernel/pic.o \
         kernel/pit.o \
         kernel/vsprintf.o \
         kernel/string.o \
         kernel/paging.o \
         kernel/rb_tree.o \
         kernel/mem_alloc.o \
         kernel/kheap.o \
         kernel/serial.o \
         kernel/logging.o \
         kernel/keyboard.o \
         kernel/vfs.o \
         kernel/vnode.o \
         kernel/initrd.o \
         kernel/thread.o \
         kernel/process.o \
         kernel/scheduler.o \
         kernel/syscall.o
