KOBJS += kernel/bootstrap.o \
         kernel/main.o \
         kernel/cpu.o \
         kernel/gdt.o \
         kernel/utils.o \
         kernel/arch.o \
         kernel/archs.o \
         kernel/idt.o \
         kernel/interrupts.o \
         kernel/vga.o \
         kernel/pic.o \
         kernel/pit.o \
         kernel/vsprintf.o \
         kernel/string.o \
         kernel/phys_mem.o \
         kernel/virt_mem.o \
         kernel/serial.o \
         kernel/logging.o \
         kernel/keyboard.o
